[package]
edition = "2021"
name = "maelstrom"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
shrinkwraprs = "0.3.0"

[dev-dependencies]
indoc = "2.0.1"
