[package]
edition = "2021"
name = "echo"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
maelstrom = {path = "../maelstrom"}
serde = "1.0.163"
serde_derive = "1.0.163"
tokio = {version = "1.28.1", features = ["full"]}
